---
version: "3"

vars:
  NODE: ./node

tasks:
  default:
    - task: serve

  build:
    desc: Build static files.
    cmds:
      - nix build

  node2nix:
    desc: Update Node.js dependencies.
    cmds:
      - >-
        node2nix
        --input {{ .NODE }}/packages.json
        --node-env {{ .NODE }}/node-env.nix
        --composition {{ .NODE }}/default.nix
        --output {{ .NODE }}/node-packages.nix

  serve:
    desc: Serve decks.
    cmds:
      - nix run ./ -- --config src/config.js --server --input-dir src/
