---
version: "3"

vars:
  MARP: "marp -c config.js --html"
  DECKS: ./docs

tasks:
  default:
    - task: serve

  up:
    desc: Run nix-shell and task runner. Assumes taskfile installed locally.
    cmds:
      - nix-shell --run "task"

  build:
    desc: Build static files.
    cmds:
      - "{{ .MARP }} --input-dir {{ .DECKS }}"
      - "{{ .MARP }} --allow-local-files --pdf {{ .DECKS }}"

  serve:
    desc: Serve decks.
    cmds:
      - "{{ .MARP }} --server --input-dir {{ .DECKS }}/"
